// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1L065AC5OBQdczVLA3GjjmIupcC-3wJ0',
    appId: '1:113359343388:web:4ca1f7dc6f7c1bc4e0f4d9',
    messagingSenderId: '113359343388',
    projectId: 'cantinaetec-14d40',
    authDomain: 'cantinaetec-14d40.firebaseapp.com',
    storageBucket: 'cantinaetec-14d40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANyCOC0CgJCSpUpy86f71_dw4-ofTAdCs',
    appId: '1:113359343388:android:528f88919d24e226e0f4d9',
    messagingSenderId: '113359343388',
    projectId: 'cantinaetec-14d40',
    storageBucket: 'cantinaetec-14d40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAJhzSR3A35l9ZTJwsfe9Otk18LruJUz0',
    appId: '1:113359343388:ios:6745a96ec4e5eac9e0f4d9',
    messagingSenderId: '113359343388',
    projectId: 'cantinaetec-14d40',
    storageBucket: 'cantinaetec-14d40.appspot.com',
    iosClientId: '113359343388-rn315v717rbrftkbq4fnq4d34br66beb.apps.googleusercontent.com',
    iosBundleId: 'br.com.etec.cantina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAJhzSR3A35l9ZTJwsfe9Otk18LruJUz0',
    appId: '1:113359343388:ios:6745a96ec4e5eac9e0f4d9',
    messagingSenderId: '113359343388',
    projectId: 'cantinaetec-14d40',
    storageBucket: 'cantinaetec-14d40.appspot.com',
    iosClientId: '113359343388-rn315v717rbrftkbq4fnq4d34br66beb.apps.googleusercontent.com',
    iosBundleId: 'br.com.etec.cantina',
  );
}
